In [1]:
import tensorflow as tf

In [2]:
x = tf.constant(3.0)
# y = x ^ 2
with tf.GradientTape() as t:
  t.watch(x)
  y = x * x
# dy = 2x
dy_dx = t.gradient(y, x)
dy_dx.numpy()

6.0

In [3]:
x = tf.constant([3.0, 3.0])

with tf.GradientTape() as t:
  t.watch(x)
  z = tf.multiply(x, x)

print(z)

# Find derivative of z with respect to the original input tensor x
print(t.gradient(z, x))

tf.Tensor([9. 9.], shape=(2,), dtype=float32)
tf.Tensor([6. 6.], shape=(2,), dtype=float32)


In [4]:
x = tf.Variable(1.0)  # Create a Tensorflow variable initialized to 1.0

with tf.GradientTape() as t:
    with tf.GradientTape() as t2:
        y = x * x * x

    # Compute the gradient inside the 't' context manager
    # which means the gradient computation is differentiable as well.
    dy_dx = t2.gradient(y, x)
d2y_dx2 = t.gradient(dy_dx, x)

print("dy_dx:", dy_dx.numpy())  # 3.0
print("d2y_dx2:", d2y_dx2.numpy())  # 6.0

dy_dx: 3.0
d2y_dx2: 6.0


In [5]:
@tf.function
def f(x, y):
    return x ** 2 + y
x = tf.constant([2],dtype=tf.float32)
y = tf.constant([3],dtype=tf.float32)
f(x, y)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([7.], dtype=float32)>

In [6]:
x = tf.Variable([1,2,3],dtype=tf.float32)
y = tf.Variable([1,2,3],dtype=tf.float32)
with tf.GradientTape(persistent=True) as t:
    z = f(x, y)
print(z)
print(t.gradient(z, x)) # dz/dx at x = 1
print(t.gradient(z, y))

tf.Tensor([ 2.  6. 12.], shape=(3,), dtype=float32)
tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
