In [1]:
import tensorflow as tf

In [2]:
@tf.function
def shift_left_one_hot(vec, shift=-1):
    P = tf.eye(tf.shape(vec)[0])
    P = tf.roll(P, shift=shift, axis=0)
    
    vec = tf.expand_dims(vec, 0)
    
    return vec @ P

vec1 = tf.Variable([0,1,0], dtype=tf.float32)
vec2 = tf.Variable([0.5,0.5,0], dtype=tf.float32)
vec3 = tf.Variable([0,0,1], dtype=tf.float32)

with tf.GradientTape(persistent=True) as tape:
    nv1 = shift_left_one_hot(vec1)
    nv2 = shift_left_one_hot(vec2)
    nv3 = shift_left_one_hot(vec3)

tf.print(nv1, tape.gradient(nv1, vec1))
tf.print(nv2, tape.gradient(nv2, vec2))
tf.print(nv3, tape.gradient(nv3, vec3))

[[0 0 1]] [1 1 1]
[[0 0.5 0.5]] [1 1 1]
[[1 0 0]] [1 1 1]
